
all: plain-numbers centered-numbers remainders dots

plain-numbers:
	lualatex plain-numbers.tex

centered-numbers:
	lualatex centered-numbers.tex

remainders:
	lualatex remainders.tex

dots:
	lualatex dots.tex
