
complete: first-column mirrored-clusters mirror-segment odd-row principal-cluster zero-hole dual-of-mirror-segment alternating-row

first-column:
	$(MAKE) -C first-column/

mirrored-clusters:
	$(MAKE) -C mirrored-clusters/

mirror-segment:
	$(MAKE) -C mirror-segment/

odd-row:
	$(MAKE) -C odd-row/

principal-cluster:
	$(MAKE) -C principal-cluster/

zero-hole:
	$(MAKE) -C zero-hole/

dual-of-mirror-segment:
	$(MAKE) -C dual-of-mirror-segment/

alternating-row:
	$(MAKE) -C alternating-row/
