
complete: multiples-over-antidiagonal zero-holes main-idea-four-splitted

multiples-over-antidiagonal:
	$(MAKE) -C multiples-over-antidiagonal/

zero-holes:
	$(MAKE) -C zero-holes/

main-idea-four-splitted:
	$(MAKE) -C main-idea-four-splitted/
