
pascal-coloured:
	cp coloured.tex predefined-colour-table.tex pascal/
	cd pascal && bash pascal.sh && lualatex coloured.tex

fibonacci-coloured:
	cp coloured.tex predefined-colour-table.tex fibonacci/
	cd fibonacci && bash fibonacci.sh && lualatex coloured.tex

catalan-coloured:
	cp coloured.tex predefined-colour-table.tex catalan/
	cd catalan && bash catalan.sh && lualatex coloured.tex

motzkin-coloured:
	cp coloured.tex predefined-colour-table.tex motzkin/
	cd motzkin && bash motzkin.sh && lualatex coloured.tex

pattern-11100-coloured:
	cp coloured.tex predefined-colour-table.tex pattern-11100/
	cd pattern-11100 && bash pattern-11100.sh && lualatex coloured.tex

pattern-101-coloured:
	cp coloured.tex predefined-colour-table.tex pattern-101/
	cd pattern-101 && bash pattern-101.sh && lualatex coloured.tex
