

start-jupyter-server:
	# the following path should be adjusted if some problem arises, for example modules in the `python-libs` are not available
	PYTHONPATH=../../../../programming-contests/competitive-programming/python-libs/ jupyter-notebook --no-browser --port=5901 --ip=150.217.37.116

