
# former rule in order to make the presentation if no
# rule is passed to `make'
conference:
	lualatex conference-ornate-20min.en.tex 

complete: catalan-tikz conference

catalan-tikz:
	$(MAKE) -C catalan-tikz/



