

all:
	lualatex --shell-escape modular-article.tex

complete:
	lualatex --shell-escape modular-article.tex
	bibtex modular-article
	lualatex --shell-escape modular-article.tex
	lualatex --shell-escape modular-article.tex
