
all: pascal-zero-rows-above-end pascal-zero-row-26

pascal-zero-rows-above-end:
	lualatex pascal-standard-mod3-zero-row-above-end.tex
	lualatex pascal-inverse-mod3-zero-row-above-end.tex

pascal-zero-row-26:
	#lualatex pascal-standard-mod3-zero-row-26.tex
	lualatex pascal-inverse-mod3-zero-row-26.tex
