
all: pascal-zero-rows-above-end pascal-zero-row-26 pascal-mod5-first-25-rows pascal-mod5-first-25-rows-for-sierpinski pascal-mod5-first-25-rows-for-sierpinski-odd-rows pascal-mod5-first-25-rows-for-sierpinski-zero-hole pascal-mod7-zero-hole

pascal-zero-rows-above-end:
	lualatex pascal-standard-mod3-zero-row-above-end.tex
	lualatex pascal-inverse-mod3-zero-row-above-end.tex

pascal-zero-row-26:
	lualatex pascal-standard-mod3-zero-row-26.tex
	lualatex pascal-inverse-mod3-zero-row-26.tex

pascal-mod5-first-25-rows:
	lualatex pascal-standard-handle-negatives-centered-colouring-127-rows-mod5-partitioning-triangle.tex

pascal-mod5-first-25-rows-for-sierpinski:
	lualatex pascal-standard-handle-negatives-centered-colouring-127-rows-mod5-partitioning-for-sierpinski-triangle.tex

pascal-mod5-first-25-rows-for-sierpinski-odd-rows:
	lualatex pascal-standard-handle-negatives-centered-colouring-127-rows-mod5-partitioning-for-sierpinski-odd-rows-triangle.tex

pascal-mod5-first-25-rows-for-sierpinski-zero-hole:
	lualatex pascal-standard-handle-negatives-centered-colouring-127-rows-mod5-partitioning-for-sierpinski-zero-hole-triangle.tex

pascal-mod7-zero-hole:
	lualatex pascal-mod7-abstracting-zero-holes

pascal-mod7-zero-hole-strip:
	lualatex pascal-mod7-abstracting-zero-holes-strip

